name: auto-tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.11.8]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Create virtual environment
        run: python3.11 -m venv .venv
      - name: Activate virtual environment
        run: source .venv/bin/activate
      - name: Install dependencies
        run: |
          pip install poetry
          poetry add pytest
          pip install pytest-cov
          pip install pyyaml
          poetry add pyyaml
          poetry add flake8
          make install
      - name: Run linter and pytest
        run: |
          make check
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
